runtime: python312

entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT 

env_variables:
  GOOGLE_API_KEY: "GOOGLE_API_KEY" 

instance_class: F2  # 필요 시 B1, F1 등으로 조절 가능

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto

